import { useEffect, useState } from "react";
import { API_BASE } from "@/lib/api-base";

type Card = { id: number; slug: string; groomName: string; brideName: string; weddingDate: string | null };
type Entry = { id: number; guestName: string; message: string | null; attendance: string; guestCount: number; isRead: boolean; moderationStatus: string; createdAt: string };

function authHeaders(extra?: HeadersInit): HeadersInit { const token = localStorage.getItem("amazingStudioToken_v2"); return { ...extra, ...(token ? { Authorization: `Bearer ${token}` } : {}) }; }

export default function CmsWeddingResponsesPage() {
  const [cards, setCards] = useState<Card[]>([]);
  const [cardId, setCardId] = useState<number | null>(null);
  const [data, setData] = useState<{ summary: Record<string, number>; entries: Entry[] } | null>(null);
  const [attendance, setAttendance] = useState("");
  const [search, setSearch] = useState("");
  useEffect(() => { fetch(`${API_BASE}/api/wedding-cards/admin/cards`, { headers: authHeaders() }).then((r) => r.json()).then((rows: Card[]) => { setCards(rows); const requested = Number(new URLSearchParams(location.search).get("card")); setCardId(rows.find((x) => x.id === requested)?.id ?? rows[0]?.id ?? null); }); }, []);
  useEffect(() => { if (!cardId) return; const params = new URLSearchParams(); if (attendance) params.set("attendance", attendance); if (search) params.set("search", search); fetch(`${API_BASE}/api/wedding-cards/admin/cards/${cardId}/guest-entries?${params}`, { headers: authHeaders() }).then((r) => r.json()).then(setData); }, [cardId, attendance, search]);
  const update = async (id: number, body: object) => { await fetch(`${API_BASE}/api/wedding-cards/admin/guest-entries/${id}`, { method: "PATCH", headers: authHeaders({ "Content-Type": "application/json" }), body: JSON.stringify(body) }); setData((current) => current ? { ...current, entries: current.entries.map((entry) => entry.id === id ? { ...entry, ...body } : entry) } : current); };
  const labels: Record<string, string> = { totalResponses: "Tổng phản hồi", attendingGuests: "Khách tham dự", expectedPeople: "Người dự kiến", declinedGuests: "Không tham dự", unknownGuests: "Chưa xác định", unread: "Chưa đọc" };
  return <main className="p-4 md:p-6 space-y-5"><div><h1 className="text-2xl font-semibold">Lời chúc & xác nhận tham dự</h1><p className="text-sm text-muted-foreground">Thiệp cưới online → chọn thiệp → quản lý phản hồi</p></div><select className="border rounded-lg p-2" value={cardId ?? ""} onChange={(e) => setCardId(Number(e.target.value))}>{cards.map((card) => <option key={card.id} value={card.id}>{card.groomName} & {card.brideName} · {card.weddingDate ?? "Chưa có ngày"}</option>)}</select>{data && <><div className="grid grid-cols-2 md:grid-cols-6 gap-3">{Object.entries(data.summary).map(([key, value]) => <div key={key} className="rounded-xl border bg-white p-3"><p className="text-xs text-muted-foreground">{labels[key] ?? key}</p><p className="text-2xl font-semibold">{value}</p></div>)}</div><div className="flex flex-wrap gap-2"><input className="border rounded-lg p-2" placeholder="Tìm theo tên" value={search} onChange={(e) => setSearch(e.target.value)} /><select className="border rounded-lg p-2" value={attendance} onChange={(e) => setAttendance(e.target.value)}><option value="">Tất cả trạng thái</option><option value="yes">Tham dự</option><option value="no">Không tham dự</option><option value="unknown">Chưa rõ</option></select></div><div className="overflow-x-auto rounded-xl border bg-white"><table className="w-full text-sm"><thead><tr className="text-left border-b"><th className="p-3">Khách</th><th className="p-3">Lời chúc</th><th className="p-3">Xác nhận</th><th className="p-3">Thời gian</th><th className="p-3">Thao tác</th></tr></thead><tbody>{data.entries.map((entry) => <tr key={entry.id} className={`border-b ${entry.isRead ? "" : "bg-rose-50"}`}><td className="p-3 font-medium">{entry.guestName}</td><td className="p-3 max-w-md">{entry.message}</td><td className="p-3">{entry.attendance === "yes" ? `Tham dự · ${entry.guestCount}` : entry.attendance === "no" ? "Không tham dự" : "Chưa rõ"}</td><td className="p-3">{new Date(entry.createdAt).toLocaleString("vi-VN")}</td><td className="p-3 space-x-2"><button className="underline" onClick={() => update(entry.id, { isRead: !entry.isRead })}>{entry.isRead ? "Chưa đọc" : "Đã đọc"}</button><button className="underline text-red-700" onClick={() => update(entry.id, { moderationStatus: entry.moderationStatus === "hidden" ? "approved" : "hidden" })}>{entry.moderationStatus === "hidden" ? "Hiện" : "Ẩn"}</button></td></tr>)}</tbody></table></div></>}</main>;
}
