export const LOGGER_REDACT_PATHS = [
  "req.headers.authorization",
  "req.headers.cookie",
  "req.body.password",
  "req.body.currentPassword",
  "req.body.newPassword",
  "req.body.credential",
  "res.headers['set-cookie']",
  "*.password",
  "*.credential",
  "*.accessToken",
  "*.refreshToken",
  "*.access_token",
  "*.refresh_token",
  "*.token",
  "*.token_hash",
  "*.csrfToken",
  "*.csrf_token",
  "*.secret",
  "*.secret_ref",
  "*.connectionString",
  "*.connection_string",
  "*.databaseUrl",
  "*.database_url",
] as const;
