import { Router, type IRouter } from "express";
import codexRouter from "./codex";
import healthRouter from "./health";
import authRouter from "./auth";
import platformAuthRouter from "./platform-auth";
import tenantMembersRouter from "./tenant-members";
import { businessAuthGuard } from "../middlewares/platform-auth";
import { signCmsPublicMediaResponses } from "../lib/cms-public-media";
import customersRouter from "./customers";
import bookingsRouter from "./bookings";
import bookingOccurrencesRouter from "./booking-occurrences";
import searchRouter from "./search";
import dressesRouter from "./dresses";
import rentalsRouter from "./rentals";
import bookingDressesRouter from "./booking-dresses";
import paymentsRouter from "./payments";
import dashboardRouter from "./dashboard";
import tasksRouter from "./tasks";
import quotesRouter from "./quotes";
import servicesRouter from "./services";
import accountingRouter from "./accounting";
import staffRouter from "./staff";
import settingsRouter from "./settings";
import expensesRouter from "./expenses";
import fixedCostsRouter from "./fixed-costs";
import contractsRouter from "./contracts";
import payrollsRouter from "./payrolls";
import pricingRouter from "./pricing";
import salaryRatesRouter from "./salary-rates";
import staffRatesRouter from "./staff-rates";
import staffCastRouter from "./staff-cast";
import staffCommissionsRouter from "./staff-commissions";
import jobEarningsRouter from "./job-earnings";
import staffProfileRouter from "./staff-profile";
import photoshopJobsRouter from "./photoshop-jobs";
import internalCommsRouter from "./internal-comms";
import storageRouter from "./storage";
import revenueRouter from "./revenue";
import bookingExtrasRouter from "./booking-extras";
import attendanceRouter from "./attendance";
import crmLeadsRouter from "./crm-leads";
import webhookFacebookRouter from "./webhook-facebook";
import fbInboxRouter from "./fb-inbox";
import aiRouter from "./ai";
import aiScriptsRouter from "./ai-scripts";
import aiTestRouter from "./ai-test";
import claudeSaleTestRouter from "./claude-sale-test";
import claudeSaleSettingsRouter from "./claude-sale-settings";
import saleLearningRouter from "./sale-learning";
import luluHumanReviewRouter from "./lulu-human-review";
import luluBrainLabRouter from "./lulu-brain-lab";
import saleScriptsRouter from "./sale-scripts";
import notificationsRouter from "./notifications";
import webPushRouter from "./web-push";
import cmsRouter from "./cms";
import photoIdeasRouter from "./photo-ideas";
import visualAdvisorRouter from "./visual-advisor";
import weddingCardsRouter from "./wedding-cards";
import staffAllowancesRouter from "./staff-allowances";
import goldenHourRouter from "./golden-hour";
import autoPostFacebookRouter from "./auto-post-facebook";

const router: IRouter = Router();

// Auth/session routes tự có guard riêng và phải đứng trước default-deny business gate.
router.use(platformAuthRouter);
router.use(authRouter);
router.use(tenantMembersRouter);

// Mọi API nghiệp vụ phía dưới mặc định cần phiên hợp lệ, trừ allowlist public
// theo đúng method/path trong middleware. Chặn các route cũ từng để hở.
router.use(businessAuthGuard);
// Response signer có truy vấn CMS registry nên chỉ được cài sau khi tenant DB
// context đã được business guard bind (kể cả các route public).
router.use(signCmsPublicMediaResponses);
router.use(healthRouter);
router.use(customersRouter);
router.use(bookingsRouter);
router.use(bookingOccurrencesRouter);
router.use(searchRouter);
router.use(dressesRouter);
router.use(rentalsRouter);
router.use(bookingDressesRouter);
router.use(paymentsRouter);
router.use(dashboardRouter);
router.use(tasksRouter);
router.use(quotesRouter);
router.use(servicesRouter);
router.use(accountingRouter);
router.use(staffProfileRouter);
router.use(staffRouter);
router.use(settingsRouter);
router.use(expensesRouter);
router.use(fixedCostsRouter);
router.use(contractsRouter);
router.use(payrollsRouter);
router.use(pricingRouter);
router.use(salaryRatesRouter);
router.use(staffRatesRouter);
router.use(staffCastRouter);
router.use(staffCommissionsRouter);
router.use(jobEarningsRouter);
router.use(photoshopJobsRouter);
router.use(internalCommsRouter);
router.use(storageRouter);
router.use(revenueRouter);
router.use(bookingExtrasRouter);
router.use(attendanceRouter);
router.use(crmLeadsRouter);
router.use(webhookFacebookRouter);
router.use(fbInboxRouter);
router.use(aiRouter);
router.use(aiScriptsRouter);
router.use(aiTestRouter);
router.use(claudeSaleTestRouter);
router.use(claudeSaleSettingsRouter);
router.use(saleLearningRouter);
router.use(luluHumanReviewRouter);
router.use(luluBrainLabRouter);
router.use(saleScriptsRouter);
router.use(notificationsRouter);
router.use(webPushRouter);
router.use(cmsRouter);
router.use(photoIdeasRouter);
router.use(visualAdvisorRouter);
router.use(weddingCardsRouter);
router.use(staffAllowancesRouter);
router.use(goldenHourRouter);
router.use(autoPostFacebookRouter);

router.use(codexRouter);
export default router;
