import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import customersRouter from "./customers";
import bookingsRouter from "./bookings";
import dressesRouter from "./dresses";
import rentalsRouter from "./rentals";
import bookingDressesRouter from "./booking-dresses";
import paymentsRouter from "./payments";
import dashboardRouter from "./dashboard";
import tasksRouter from "./tasks";
import quotesRouter from "./quotes";
import servicesRouter from "./services";
import accountingRouter from "./accounting";
import staffRouter from "./staff";
import settingsRouter from "./settings";
import expensesRouter from "./expenses";
import fixedCostsRouter from "./fixed-costs";
import contractsRouter from "./contracts";
import payrollsRouter from "./payrolls";
import pricingRouter from "./pricing";
import salaryRatesRouter from "./salary-rates";
import staffRatesRouter from "./staff-rates";
import staffCastRouter from "./staff-cast";
import staffCommissionsRouter from "./staff-commissions";
import jobEarningsRouter from "./job-earnings";
import staffProfileRouter from "./staff-profile";
import photoshopJobsRouter from "./photoshop-jobs";
import internalCommsRouter from "./internal-comms";
import storageRouter from "./storage";
import revenueRouter from "./revenue";
import bookingExtrasRouter from "./booking-extras";
import attendanceRouter from "./attendance";
import crmLeadsRouter from "./crm-leads";
import webhookFacebookRouter from "./webhook-facebook";
import fbInboxRouter from "./fb-inbox";
import aiRouter from "./ai";
import aiScriptsRouter from "./ai-scripts";
import aiTestRouter from "./ai-test";
import notificationsRouter from "./notifications";
import webPushRouter from "./web-push";
import cmsRouter from "./cms";
import weddingCardsRouter from "./wedding-cards";
import staffAllowancesRouter from "./staff-allowances";

const router: IRouter = Router();

router.use(authRouter);
router.use(healthRouter);
router.use(customersRouter);
router.use(bookingsRouter);
router.use(dressesRouter);
router.use(rentalsRouter);
router.use(bookingDressesRouter);
router.use(paymentsRouter);
router.use(dashboardRouter);
router.use(tasksRouter);
router.use(quotesRouter);
router.use(servicesRouter);
router.use(accountingRouter);
router.use(staffProfileRouter);
router.use(staffRouter);
router.use(settingsRouter);
router.use(expensesRouter);
router.use(fixedCostsRouter);
router.use(contractsRouter);
router.use(payrollsRouter);
router.use(pricingRouter);
router.use(salaryRatesRouter);
router.use(staffRatesRouter);
router.use(staffCastRouter);
router.use(staffCommissionsRouter);
router.use(jobEarningsRouter);
router.use(photoshopJobsRouter);
router.use(internalCommsRouter);
router.use(storageRouter);
router.use(revenueRouter);
router.use(bookingExtrasRouter);
router.use(attendanceRouter);
router.use(crmLeadsRouter);
router.use(webhookFacebookRouter);
router.use(fbInboxRouter);
router.use(aiRouter);
router.use(aiScriptsRouter);
router.use(aiTestRouter);
router.use(notificationsRouter);
router.use(webPushRouter);
router.use(cmsRouter);
router.use(weddingCardsRouter);
router.use(staffAllowancesRouter);

export default router;
