import { useEffect, useState } from "react";
import { CheckCircle2, Clock3, Code2, Loader2, XCircle } from "lucide-react";
import { getApiBase } from "@/lib/api-base";
import { useStaffAuth } from "@/contexts/StaffAuthContext";
import X20SettingsDrawer from "../components/ai-codex/x20-settings-drawer";

type Task = { task_id: string; user_request: string; mode: string; status: string; output?: string | null; diff?: string | null; test_result?: string | null; error?: string | null };
const terminal = new Set(["COMPLETED", "FAILED"]);
export default function AiCodexPage() {
  const { viewer } = useStaffAuth();
  const [request, setRequest] = useState(""); const [mode, setMode] = useState("readonly");
  const [task, setTask] = useState<Task | null>(null); const [history, setHistory] = useState<Task[]>([]); const [loading, setLoading] = useState(false);
  const [provider, setProvider] = useState("codex"); const [x20Open, setX20Open] = useState(false);
  const api = getApiBase(); const auth = () => ({ authorization: `Bearer ${localStorage.getItem("amazingStudioToken_v2") || ""}`, "content-type": "application/json" });
  useEffect(() => { if (!task || terminal.has(task.status)) return; const id = window.setInterval(async () => { const r = await fetch(`${api}/api/codex/tasks/${task.task_id}`, { headers: auth() }); if (r.ok) setTask(await r.json()); }, 2500); return () => clearInterval(id); }, [task?.task_id, task?.status]);
  async function submit() { if (!request.trim() || loading) return; setLoading(true); try { const r = await fetch(`${api}/api/codex/tasks`, { method: "POST", headers: auth(), body: JSON.stringify({ project: "amazing-studio", user_request: request.trim(), mode }) }); const t = await r.json(); setTask(t); setHistory(h => [t, ...h]); } finally { setLoading(false); } }
  async function action(kind: "approve" | "cancel") { if (!task) return; const r = await fetch(`${api}/api/codex/tasks/${task.task_id}/${kind}`, { method: "POST", headers: auth() }); if (r.ok) setTask(await r.json()); }
  if (!viewer) return null;
  return <main className="mx-auto w-full max-w-5xl space-y-6 p-4 sm:p-8">
    <header data-preview="real-ai-codex" className="space-y-3"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[.22em] text-primary">Amazing Studio</p><h1 className="mt-2 flex items-center gap-3 text-3xl font-bold"><Code2 className="h-8 w-8" />AI Codex</h1></div><div className="flex flex-wrap gap-2"><select value={provider} onChange={e => setProvider(e.target.value)} className="rounded-lg border bg-background px-3 py-2"><option value="codex">Codex hiá»‡n táº¡i â€” chÆ°a xÃ¡c minh tÃ i khoáº£n</option><option value="x20" disabled>AMAZINGSTUDIO / X20</option><option disabled>Tá»± Ä‘á»™ng chá»n</option></select><button onClick={() => setX20Open(true)} className="rounded-lg border px-3 py-2 font-semibold">âš™ CÃ i Ä‘áº·t X20</button></div></div><p className="text-muted-foreground">Giao viá»‡c cho Codex trÃªn VPS. Bridge token vÃ  credential khÃ´ng rá»i backend.</p></header>
    <section className="rounded-2xl border bg-card p-4 shadow-sm"><textarea value={request} onChange={e => setRequest(e.target.value)} placeholder="VÃ­ dá»¥: Kiá»ƒm tra lá»—i Thu tiá»n..." className="min-h-32 w-full resize-y rounded-xl border bg-background p-3 outline-none focus:ring-2 focus:ring-primary" /><div className="mt-3 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><select value={mode} onChange={e => setMode(e.target.value)} className="rounded-lg border bg-background px-3 py-2"><option value="readonly">CHá»ˆ KIá»‚M TRA Â· READ_ONLY</option><option value="test">Sá»¬A + TEST Â· FIX</option><option value="fix_and_stage">CHUáº¨N Bá»Š ÄÆ¯A LÃŠN APP Â· FIX_AND_STAGE</option></select><button disabled={loading || !request.trim()} onClick={submit} className="rounded-lg bg-primary px-5 py-2 font-semibold text-primary-foreground disabled:opacity-50">{loading ? "Äang gá»­i..." : "Gá»­i cho Codex"}</button></div></section>
    {task && <section className="space-y-4 rounded-2xl border bg-card p-4 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm text-muted-foreground">Task {task.task_id}</p><h2 className="text-xl font-semibold">{task.status}</h2></div><StatusIcon status={task.status} /></div><div className="grid gap-3 text-sm sm:grid-cols-4">{["QUEUED", "ANALYZING", "CODING", "TESTING"].map(s => <div key={s} className={`rounded-lg border p-3 ${task.status === s ? "border-primary bg-primary/5" : ""}`}>{s}</div>)}</div>{task.status === "WAITING_APPROVAL" && <button onClick={() => action("approve")} className="rounded-lg bg-amber-500 px-4 py-2 font-semibold text-white">Duyá»‡t task</button>}{!terminal.has(task.status) && <button onClick={() => action("cancel")} className="ml-2 rounded-lg border px-4 py-2">Há»§y</button>}<div className="rounded-xl bg-muted/50 p-4 text-sm"><p className="font-semibold">Káº¿t quáº£ Codex</p><pre className="mt-2 max-h-72 overflow-auto whitespace-pre-wrap">{task.output || task.error || "Äang chá» káº¿t quáº£..."}</pre><p className="mt-3"><b>Test:</b> {task.test_result || "ChÆ°a cÃ³"}</p><p><b>Diff:</b> {task.diff || "KhÃ´ng cÃ³ thay Ä‘á»•i"}</p><p><b>Production:</b> ChÆ°a tá»± Ä‘á»™ng deploy</p></div></section>}
    <section><h2 className="mb-3 text-lg font-semibold">Lá»‹ch sá»­ task</h2>{history.map(t => <div key={t.task_id} className="mb-2 flex items-center justify-between rounded-xl border p-3 text-sm"><span className="truncate pr-3">{t.user_request}</span><span className="font-semibold">{t.status}</span></div>)}</section>
    <X20SettingsDrawer open={x20Open} onClose={() => setX20Open(false)} />
  </main>;
}
function StatusIcon({ status }: { status: string }) { if (status === "COMPLETED") return <CheckCircle2 className="text-emerald-600" />; if (status === "FAILED") return <XCircle className="text-red-600" />; if (status === "QUEUED") return <Clock3 className="text-amber-600" />; return <Loader2 className="animate-spin text-primary" />; }
