import { useEffect, useState } from "react";
import { API_BASE } from "@/lib/api-base";
import { useStaffAuth } from "@/contexts/StaffAuthContext";

type Signup = { id:string; tenant_id?:string|null; studio_name:string; owner_name:string; phone:string; email:string; address?:string; requested_plan_code:string; status:string; created_at:string };
type Studio = { id:string; name:string; slug:string; status:string; plan_code?:string; subscription_status?:string; current_period_ends_at?:string; registry_status?:string; provisioning_status?:string; provisioning_step?:string; provisioning_failed_step?:string; provisioning_error_code?:string; provisioning_error_message?:string; provisioning_last_attempted_at?:string };
type Confirmation = { key:string; label:string; work:()=>Promise<Response> };

const trialDaysRemaining=(studio:Studio)=>studio.current_period_ends_at?
  Math.max(0,Math.ceil((new Date(studio.current_period_ends_at).getTime()-Date.now())/86_400_000)):0;

export default function PlatformAdminPage() {
  const { platformUser, csrfToken, logout } = useStaffAuth();
  const [stats,setStats]=useState<Record<string,number>>({}); const [signups,setSignups]=useState<Signup[]>([]); const [studios,setStudios]=useState<Studio[]>([]); const [error,setError]=useState(""); const [pending,setPending]=useState(""); const [confirmation,setConfirmation]=useState<Confirmation|null>(null);
  const allowed = platformUser?.platformRole === "PLATFORM_OWNER";
  const load = async () => {
    const [a,b,c]=await Promise.all([fetch(`${API_BASE}/api/platform-admin/api/dashboard`,{credentials:"include"}),fetch(`${API_BASE}/api/platform-admin/api/signups`,{credentials:"include"}),fetch(`${API_BASE}/api/platform-admin/api/studios`,{credentials:"include"})]);
    if(!a.ok||!b.ok||!c.ok) throw new Error(a.status===403||b.status===403||c.status===403?"Không có quyền Platform Owner":"Không tải được Platform Admin");
    setStats(await a.json()); setSignups(await b.json()); setStudios(await c.json());
  };
  useEffect(()=>{ if(allowed) void load().catch(e=>setError(e.message)); },[allowed]);
  const run=(key:string,label:string,work:()=>Promise<Response>)=>{if(!pending)setConfirmation({key,label,work});};
  const confirmRun=async()=>{const selected=confirmation;if(!selected||pending)return;setConfirmation(null);setPending(selected.key);setError("");try{const r=await selected.work();const p=await r.json().catch(()=>({})) as {error?:string};if(!r.ok)throw new Error(p.error||"Không xử lý được");await load();}catch(e){setError(e instanceof Error?e.message:"Không xử lý được");}finally{setPending("");}};
  const act=(signup:Signup,action:string)=>run(`signup:${signup.id}`,`${action} yêu cầu ${signup.studio_name}`,()=>fetch(`${API_BASE}/api/platform-admin/api/signups/${signup.id}/${action}`,{method:"POST",credentials:"include",headers:{"X-CSRF-Token":csrfToken||""}}));
  const studioAct=(studio:Studio,action:string,extra:Record<string,unknown>={})=>run(`studio:${studio.id}`,`${action} studio ${studio.name}`,()=>fetch(`${API_BASE}/api/platform-admin/api/studios/${studio.id}/action`,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrfToken||""},body:JSON.stringify({action,...extra})}));
  if(!allowed)return <main className="min-h-screen p-8"><h1 className="text-2xl font-bold">403 — Không có quyền</h1></main>;
  return <main className="min-h-screen bg-slate-50 p-4 md:p-8">{confirmation&&<div role="dialog" aria-modal="true" aria-label="Xác nhận thao tác" className="fixed inset-0 z-50 grid place-items-center bg-black/40 p-4"><div className="w-full max-w-md rounded-xl bg-white p-6 shadow-xl"><h2 className="text-lg font-bold">Xác nhận thao tác</h2><p className="mt-2 text-sm text-slate-600">Xác nhận {confirmation.label}?</p><div className="mt-5 flex justify-end gap-2"><button onClick={()=>setConfirmation(null)} className="rounded border px-4 py-2">Hủy</button><button onClick={()=>void confirmRun()} className="rounded bg-purple-700 px-4 py-2 font-semibold text-white">Xác nhận</button></div></div></div>}<div className="mx-auto max-w-7xl"><div className="mb-6 flex justify-between"><div><h1 className="text-2xl font-bold">Platform Admin</h1><p className="text-sm text-slate-500">Commercial SaaS foundation</p></div><button onClick={()=>void logout()} className="rounded border px-3">Đăng xuất</button></div>
    {error&&<p className="mb-4 text-red-600">{error}</p>}<div className="mb-8 grid grid-cols-2 gap-3 md:grid-cols-6">{Object.entries(stats).map(([k,v])=><div key={k} className="rounded-xl bg-white p-4 shadow-sm"><div className="text-2xl font-bold">{v}</div><div className="text-xs text-slate-500">{k.replaceAll('_',' ')}</div></div>)}</div>
    <div className="overflow-x-auto rounded-xl bg-white shadow-sm"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="p-3">Studio / Owner</th><th>Liên hệ</th><th>Plan</th><th>Status</th><th>Ngày tạo</th><th>Actions</th></tr></thead><tbody>{signups.map(s=><tr key={s.id} className="border-b"><td className="p-3"><b>{s.studio_name}</b><br/>{s.owner_name}</td><td>{s.phone}<br/>{s.email}</td><td>{s.requested_plan_code}</td><td>{s.status}</td><td>{new Date(s.created_at).toLocaleDateString('vi-VN')}</td><td className="space-x-2"><button disabled={!!pending} onClick={()=>void act(s,'contact')} className="underline disabled:opacity-40">Đã liên hệ</button><button disabled={!!pending} onClick={()=>void act(s,'approve')} className="text-green-700 underline disabled:opacity-40">Duyệt</button><button disabled={!!pending} onClick={()=>void act(s,'reject')} className="text-red-700 underline disabled:opacity-40">Từ chối</button>{(s.status==='PENDING'||s.status==='CONTACTED')&&<button disabled={!!pending} onClick={()=>void act(s,'trial_override')} className="text-amber-700 underline disabled:opacity-40">Cho trial lại</button>}{s.tenant_id&&<>{(()=>{const studio=studios.find(x=>x.id===s.tenant_id);return studio?<><button disabled={!!pending} onClick={()=>void studioAct(studio,'mark_setup_paid')} className="text-blue-700 underline disabled:opacity-40">Đã thu setup</button><button disabled={!!pending} onClick={()=>void studioAct(studio,'waive_setup_fee')} className="text-amber-700 underline disabled:opacity-40">Miễn setup</button><button disabled={!!pending} onClick={()=>void studioAct(studio,'activate')} className="text-purple-700 underline disabled:opacity-40">Kích hoạt</button></>:null;})()}</>}</td></tr>)}</tbody></table></div>
    <h2 className="mb-3 mt-8 text-xl font-bold">Studios</h2><div className="overflow-x-auto rounded-xl bg-white shadow-sm"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="p-3">Studio</th><th>Plan</th><th>Subscription</th><th>Provisioning</th><th>Registry</th><th>Actions</th></tr></thead><tbody>{studios.map(s=><tr key={s.id} className="border-b"><td className="p-3"><b>{s.name}</b><br/><span className="text-xs text-slate-500">{s.slug} · {s.status}</span></td><td>{s.plan_code||'—'}</td><td>{s.subscription_status==='trial'?`TRIAL · còn ${trialDaysRemaining(s)} ngày`:(s.subscription_status||'—')}<br/><span className="text-xs">{s.current_period_ends_at?`Hết hạn: ${new Date(s.current_period_ends_at).toLocaleDateString('vi-VN')}`:'—'}</span></td><td>{s.provisioning_status||'—'} · {s.provisioning_step||'—'}{s.provisioning_error_code&&<p className="max-w-xs text-xs text-red-700">{s.provisioning_error_code}: {s.provisioning_error_message}</p>}{s.provisioning_last_attempted_at&&<span className="text-xs">{new Date(s.provisioning_last_attempted_at).toLocaleString('vi-VN')}</span>}</td><td>{s.registry_status||'chưa có'}</td><td className="space-x-2"><button disabled={!!pending} onClick={()=>void studioAct(s,'extend',{days:30})} className="underline disabled:opacity-40">+1 tháng</button><button disabled={!!pending} onClick={()=>void studioAct(s,s.status==='suspended'?'reactivate':'suspend')} className="underline disabled:opacity-40">{s.status==='suspended'?'Mở lại':'Tạm khóa'}</button><button disabled={!!pending} onClick={()=>void studioAct(s,'change_plan',{planCode:s.plan_code==='PRO'?'STANDARD':'PRO'})} className="underline disabled:opacity-40">Đổi plan</button>{s.provisioning_status==='failed'&&<button disabled={!!pending} onClick={()=>void studioAct(s,'retry_provisioning')} className="text-red-700 underline disabled:opacity-40">Retry provisioning</button>}</td></tr>)}</tbody></table></div>
  </div></main>;
}
