import { pgTable, serial, text, timestamp, numeric, boolean, integer, jsonb, index, uniqueIndex } from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";

export const autopostContentPool = pgTable("autopost_content_pool", {
  id: serial("id").primaryKey(),
  sourceType: text("source_type").notNull(),
  sourceTable: text("source_table"),
  sourceItemId: text("source_item_id"),
  contentType: text("content_type").notNull(),
  title: text("title").notNull(),
  images: jsonb("images").notNull().default(sql`'[]'::jsonb`),
  price: numeric("price", { precision: 12, scale: 2 }),
  salePrice: numeric("sale_price", { precision: 12, scale: 2 }),
  goldenHourPercent: numeric("golden_hour_percent", { precision: 5, scale: 2 }),
  goldenHourName: text("golden_hour_name"),
  category: text("category"),
  badge: text("badge"),
  publicLink: text("public_link"),
  meta: jsonb("meta").notNull().default(sql`'{}'::jsonb`),
  imageHash: text("image_hash"),
  isEligible: boolean("is_eligible").notNull().default(true),
  ineligibleReason: text("ineligible_reason"),
  lastPostedAt: timestamp("last_posted_at", { withTimezone: true }),
  timesPosted: integer("times_posted").notNull().default(0),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (t) => ({ uqSource: uniqueIndex("uq_autopost_pool_source").on(t.sourceTable, t.sourceItemId) }));

export const autopostSchedules = pgTable("autopost_schedules", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  enabled: boolean("enabled").notNull().default(false),
  pageId: text("page_id"),
  timezone: text("timezone").notNull().default("Asia/Ho_Chi_Minh"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
});

export const autopostScheduleSlots = pgTable("autopost_schedule_slots", {
  id: serial("id").primaryKey(),
  scheduleId: integer("schedule_id").notNull(),
  postTime: text("post_time").notNull(),
  contentType: text("content_type").notNull(),
  imageCount: integer("image_count").notNull().default(1),
  sourcePriority: text("source_priority").notNull().default("app_web"),
  enabled: boolean("enabled").notNull().default(true),
  sortOrder: integer("sort_order").notNull().default(0),
});

export const autopostPosts = pgTable("autopost_posts", {
  id: serial("id").primaryKey(),
  scheduleId: integer("schedule_id"),
  slotId: integer("slot_id"),
  contentPoolId: integer("content_pool_id"),
  pageId: text("page_id"),
  contentType: text("content_type"),
  images: jsonb("images").notNull().default(sql`'[]'::jsonb`),
  captionOptions: jsonb("caption_options").notNull().default(sql`'[]'::jsonb`),
  captionRecommendedIndex: integer("caption_recommended_index"),
  captionFinal: text("caption_final"),
  status: text("status").notNull().default("draft_ai"),
  scheduledAt: timestamp("scheduled_at", { withTimezone: true }),
  approvedBy: integer("approved_by"),
  approvedAt: timestamp("approved_at", { withTimezone: true }),
  postedAt: timestamp("posted_at", { withTimezone: true }),
  facebookPostId: text("facebook_post_id"),
  facebookPostLink: text("facebook_post_link"),
  errorMessage: text("error_message"),
  retryCount: integer("retry_count").notNull().default(0),
  captionHash: text("caption_hash"),
  imageHash: text("image_hash"),
  sourceType: text("source_type"),
  sourceItemId: text("source_item_id"),
  // Nâng cấp (cộng-thêm): gắn batch, vết AI, auto-approve, hold, điểm chất lượng.
  batchId: integer("batch_id"),
  aiModel: text("ai_model"),
  usedSampleIds: jsonb("used_sample_ids").notNull().default(sql`'[]'::jsonb`),
  visionImageCount: integer("vision_image_count"),
  autoApproveAt: timestamp("auto_approve_at", { withTimezone: true }),
  holdReason: text("hold_reason"),
  qualityScore: integer("quality_score"),
  generatedBy: integer("generated_by"),
  footerEnabled: boolean("footer_enabled"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (t) => ({
  byStatus: index("ix_autopost_posts_status_sched").on(t.status, t.scheduledAt),
  byBatch: index("ix_autopost_posts_batch").on(t.batchId),
  byAutoApprove: index("ix_autopost_posts_autoapprove").on(t.status, t.autoApproveAt),
}));

export const autopostBatches = pgTable("autopost_batches", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  description: text("description"),
  pageId: text("page_id"),
  sourcePriority: text("source_priority").notNull().default("app_web"),
  contentTypes: jsonb("content_types").notNull().default(sql`'[]'::jsonb`),
  tags: jsonb("tags").notNull().default(sql`'[]'::jsonb`),
  tone: text("tone"),
  mode: text("mode").notNull().default("manual"),
  postsPerDay: integer("posts_per_day").notNull().default(3),
  captionOptionsPerPost: integer("caption_options_per_post").notNull().default(3),
  slots: jsonb("slots").notNull().default(sql`'[]'::jsonb`),
  dryRun: boolean("dry_run"),
  autoApproveEnabled: boolean("auto_approve_enabled").notNull().default(false),
  autoApproveAfterMinutes: integer("auto_approve_after_minutes").notNull().default(30),
  requireManualApproval: boolean("require_manual_approval").notNull().default(true),
  autoPublishAfterApproved: boolean("auto_publish_after_approved").notNull().default(false),
  enabled: boolean("enabled").notNull().default(false),
  sortOrder: integer("sort_order").notNull().default(0),
  config: jsonb("config").notNull().default(sql`'{}'::jsonb`),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
});

export const autopostPostLog = pgTable("autopost_post_log", {
  id: serial("id").primaryKey(),
  postId: integer("post_id").notNull(),
  event: text("event").notNull(),
  detail: jsonb("detail").notNull().default(sql`'{}'::jsonb`),
  actor: text("actor"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
}, (t) => ({ byPost: index("ix_autopost_post_log_post").on(t.postId, t.createdAt) }));

export const autopostSettings = pgTable("autopost_settings", {
  id: integer("id").primaryKey().default(1),
  config: jsonb("config").notNull().default(sql`'{}'::jsonb`),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  updatedBy: integer("updated_by"),
});

export const autopostStyleSamples = pgTable("autopost_style_samples", {
  id: serial("id").primaryKey(),
  title: text("title").notNull(),
  content: text("content").notNull(),
  tags: jsonb("tags").notNull().default(sql`'[]'::jsonb`),
  contentType: text("content_type"),
  tone: text("tone"),
  isActive: boolean("is_active").notNull().default(true),
  priority: integer("priority").notNull().default(0),
  images: jsonb("images").notNull().default(sql`'[]'::jsonb`),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (t) => ({ byActive: index("ix_autopost_style_active").on(t.isActive, t.contentType, t.priority) }));
